---
# tasks file for lbrole
- name: Installing haproxy Package
  package:
        name: "{{ package_name }}"
        state: present

- name: Copying The Configuration File
  template:
        src: "templates/haproxy.cfg.j2"
        dest: "/etc/haproxy/haproxy.cfg"
  notify: Restarting Haproxy Service
        
- name: Starting The Service
  service:
        name: "{{ service_name }}"
        state: started
        enabled: yes
