---
# tasks file for webrole
- name: "Installing The WebServer"
  package:
          name: "{{ package_name }}"
          state: present

- name: "Installing PHP Interpreter"
  package:
          name: "php"
          state: present


- name: "Copying content to the webserver"
  copy:
          src: "files/web.php"
          dest: "/var/www/html/index.php"

- name: "Starting the webservice"
  service:
          name: "{{ service_name }}"
          state: started
          enabled: yes
